### ISSUE TITLE
页面加载时间过长

### ISSUE THREAD

**Issue by hujingnb** [mokeyjay/Pixiv-daily-ranking-widget#22]
当前的形式, 将所有 image 都放到 div 中, 存在如下问题: 

1. 图片的加载会影响页面加载时间
2. ifreame 加载的时候, 会下载其中的所有图片 (有时发生)

这样一来, 此组件会影响博客自身的加载时长, 体验不太好. 

修改意见: 

1. 减少首次的图片加载数量, 按需加载图片. 以保证博客自身的加载
2. 每次提前加载前后2张图片即可, 保证图片切换时的流畅度. 其他图片无需加载

实现方案可参考: [https://fun.hujingnb.com/pixiv/i](https://fun.hujingnb.com/pixiv/i), 直接看 HTML 源码就行

这里就不提 PR 啦, 我上次的 PR 已经很久没人管了😭😭

**Comment by tuzh6** [comment]
请问想把图片保存在自己搭建的服务器上，不想使用其他图床，url应该怎么填写呀

**Comment by hujingnb** [comment]
> 请问想把图片保存在自己搭建的服务器上，不想使用其他图床，url应该怎么填写呀

你可以直接使用当前项目, 图片的存储方式提供了`local`, 可以将图片直接存放在本地呀

**Comment by tuzh6** [comment]
> > 请问想把图片保存在自己搭建的服务器上，不想使用其他图床，url应该怎么填写呀
> 
> 你可以直接使用当前项目, 图片的存储方式提供了`local`, 可以将图片直接存放在本地呀

我试了试没成功😂，没有下载图片不知道是不是url填的不对，比如项目我是放在www.huluwa.xyz这个站点下面，url是不是应该填写这个站点啊

**Comment by hujingnb** [comment]
> www.huluwa.xyz

这个项目我也没搭建过, 不过代码比较简单, 自己排查一下应该还是比较容易的. 

就沿着代码的逻辑排查呗, 图片链接是否成功获取/图片是否下载成功/下载后的图片链接是否可访问 等等

如果实在无法解决, 你可以单独提一个`isuse`让对项目比较熟悉的人

**Comment by tuzh6** [comment]
> > > > 请问想把图片保存在自己搭建的服务器上，不想使用其他图床，url应该怎么填写呀
> > > 
> > > 
> > > 你可以直接使用当前项目, 图片的存储方式提供了`local`, 可以将图片直接存放在本地呀
> > 
> > 
> > 我试了试没成功joy，没有下载图片不知道是不是url填的不对，比如项目我是放在www.huluwa.xyz这个站点下面，url是不是应该填写这个站点啊
> 
> 这个项目我也没搭建过, 不过代码比较简单, 自己排查一下应该还是比较容易的.
> 
> 就沿着代码的逻辑排查呗, 图片链接是否成功获取/图片是否下载成功/下载后的图片链接是否可访问 等等
> 
> 如果实在无法解决, 你可以单独提一个`isuse`让对项目比较熟悉的人

好滴😊

**Comment by mokeyjay** [comment]
> 当前的形式, 将所有 image 都放到 div 中, 存在如下问题:
> 
> 1. 图片的加载会影响页面加载时间
> 2. ifreame 加载的时候, 会下载其中的所有图片 (有时发生)
> 
> 这样一来, 此组件会影响博客自身的加载时长, 体验不太好.
> 
> 修改意见:
> 
> 1. 减少首次的图片加载数量, 按需加载图片. 以保证博客自身的加载
> 2. 每次提前加载前后2张图片即可, 保证图片切换时的流畅度. 其他图片无需加载
> 
> 实现方案可参考: https://fun.hujingnb.com/pixiv/i, 直接看 HTML 源码就行
> 
> 这里就不提 PR 啦, 我上次的 PR 已经很久没人管了😭😭

😥啊这……我一直在等你更新 PR 呢  
刚才去看了一下，原来你早就已经更新了，我大概是漏了邮件，对不起对不起，今天一定 review 🙏

**Comment by mokeyjay** [comment]
关于你反馈的问题，早在这个项目立项之初我就考虑到懒加载的。刚才再次测试了一下
![动画](https://user-images.githubusercontent.com/6757507/208336165-6a33a4e4-3932-4a1d-88de-7422bf54b5da.gif)
目前看来懒加载是正常的哦。有什么办法可以复现那个一次性加载全部图的情况吗？

**Comment by mokeyjay** [comment]
> 请问想把图片保存在自己搭建的服务器上，不想使用其他图床，url应该怎么填写呀

就填你搭建好后，能访问到这个项目的 url 就行了。图床只保留一个 `local`

**Comment by hujingnb** [comment]
> 关于你反馈的问题，早在这个项目立项之初我就考虑到懒加载的。刚才再次测试了一下 ![动画](https://user-images.githubusercontent.com/6757507/208336165-6a33a4e4-3932-4a1d-88de-7422bf54b5da.gif) [ ![动画](https://user-images.githubusercontent.com/6757507/208336165-6a33a4e4-3932-4a1d-88de-7422bf54b5da.gif) ](https://user-images.githubusercontent.com/6757507/208336165-6a33a4e4-3932-4a1d-88de-7422bf54b5da.gif) [ ](https://user-images.githubusercontent.com/6757507/208336165-6a33a4e4-3932-4a1d-88de-7422bf54b5da.gif) （上面是个 gif 图，右侧是开发者工具） 目前看来懒加载是正常的哦。有什么办法可以复现那个一次性加载全部图的情况吗？

1. 当前只是图片懒加载, 没有图片预加载. 浏览器打开低速是会发现, 图片是在显示时才加载的. (使用的是项目 demo 地址)

![](https://p1.xywm.ltd/2022/12/19/639fcd8276424.png)

2. 一次性加载全部, 是我在将通过 ifreame 引用网站后, 博客地址刷新的时候遇到的(偶尔出现)
   * 不过我是在测试我自己搭建服务的时候碰到的, 可能当前项目已经改过了, 若不存在可忽略

**Comment by hujingnb** [comment]
关于一次性加载全部图片的问题, 我使用您提供的服务又尝试了多次, 没有再碰到. 

可能是我自己搭建服务的问题吧, 您忽略就好. 

对于预加载的问题, 您如果觉得问题不大, 直接关闭`isuse`举行

**Comment by mokeyjay** [comment]
预加载确实是有意义的，只不过图小平时感觉无所谓。前端不太熟，我研究研究👌
