### ISSUE TITLE
sm.ms维护致使图片403

### ISSUE THREAD

**Issue by qNFCp** [mokeyjay/Pixiv-daily-ranking-widget#3]
当仅开启sm.ms图床时，若sm.ms图床维护无法访问，便会引起图片不显示（直接返回P站的图片地址导致403）
log内容
06:25:41 --> {"code":"error","msg":"\u5347\u7ea7\u7ef4\u62a4\u4e2d, \u8bf7\u7a0d\u540e\u518d\u8bbf\u95ee"}
#译：升级维护中, 请稍后再访问
download是开启的

**Comment by mokeyjay** [comment]
啊，是这样的，昨天sm.ms突然被ban了备案，原因是某被举报的违法app使用了这个图床
因为sm.ms一直挺稳的所以没有做好相关处理。我会尽量在今天内解决

**Comment by qNFCp** [comment]
> 啊，是这样的，昨天sm.ms突然被禁止了备案，原因是某被举报的违法应用了使用这个图产品床
> 因为sm.ms一直挺稳的所以没有做好相关处理。我会尽量在今天内解决

23333怪不得，麻烦您了

**Comment by mokeyjay** [comment]
重新看代码才发现原来我是做了处理的，当图床挂掉时，会自动使用本地的图片链接
不过由于Pixiv开启了防盗链所以403了
这个无解，只能你自行打开`$download`配置项，把图片下载到服务器本地

**Comment by qNFCp** [comment]
> 重新看代码才发现原来我是做了处理的，当图床挂掉时，会自动使用本地的图片链接
> 不过由于Pixiv开启了防盗链所以403了
> 这个无解，只能你自行打开`$download`配置项，把图片下载到服务器本地

ummmmmm
>    public static $url_cache = TRUE;
>    public static $download = TRUE;

这个的话我一直是开着的...
另外我注意到了图片文件夹里面从sm.ms图床出问题到今天的图片都没有删掉，手动删除后重新访问，看到只缓存了六张...有点迷😂

**Comment by qNFCp** [comment]
换成了3.0，配置里面把smms图床打开了，图片缓存了22张卡住了，依旧是图片403qwq
（放弃治疗，图床关闭，加CDN.jpg）

**Comment by mokeyjay** [comment]
emmmm...你的VPS是什么情况？带宽多少？地域在哪？

**Comment by qNFCp** [comment]
Google cloud台湾 ，具体带宽多少不清楚，把图床选项关闭之后秒缓存完图片，但是开图床就会下几张然后卡住

**Comment by mokeyjay** [comment]
看看php的执行超时时间是不是设置太短了？

**Comment by qNFCp** [comment]
设的五分钟......应该不是这的问题
