### ISSUE TITLE
建议考虑添加返回高清图片的功能~

### ISSUE THREAD

**Issue by tuzh6** [mokeyjay/Pixiv-daily-ranking-widget#30]
非常好用的挂件，就是访问作品需要特定网络，如果能之间返回高清图片而不是缩略图，或者添加下载高清图片的功能就更好啦

**Comment by mokeyjay** [comment]
高清图需要登录态，比较麻烦；而且咱们小挂件那么小的面积没必要显示大图，浪费带宽

如果确实有需要，们项目也支持 api 呀 [https://pixiv.mokeyjay.com/?r=api/pixiv-json](https://pixiv.mokeyjay.com/?r=api/pixiv-json)
取里面的 `data.*.id` ，再拼接上 `https://pixiv.cat/[id].jpg` 就有大图了

例如：
![](https://pixiv.cat/113767677.jpg)
