### ISSUE TITLE
感觉可以把这个pb.nichi.co当作图床用

### ISSUE THREAD

**Issue by LanYunDev** [mokeyjay/Pixiv-daily-ranking-widget#31]
pb.nichi.co
meow - paste bin
usage: curl --data-binary @<file> https://pb.nichi.co/

**Comment by mokeyjay** [comment]
感谢提供，我试了一下，感觉不是太理想，上传的文件似乎是放在美国那边，网络高峰时期可能会疯狂爆炸。其次是没有任何有效说明，例如对待 R16 图片的态度、文件保留多久等等
