### ISSUE TITLE
官方接口是怎么了？

### ISSUE THREAD

**Issue by xiaobailoves** [mokeyjay/Pixiv-daily-ranking-widget#8]
本来是想自己搭的,但是用了香港机还是加载了半天没加载出来
因为没钱买代理IP而用官方接口的屑~一枚

**Comment by mokeyjay** [comment]
官方是指 Pixiv 还是指我？
我也刚发现我的服务器挂了……正在了解情况

**Comment by xiaobailoves** [comment]
> 官方是指 Pixiv 还是指我？
> 我也刚发现我的服务器挂了……正在了解情况

https://cloud.mokeyjay.com/pixiv
这个接口

**Comment by mokeyjay** [comment]
噢，就是我的服务器。确实挂了，原因暂时不明，正在调查😢

**Comment by xiaobailoves** [comment]
> 噢，就是我的服务器。确实挂了，原因暂时不明，正在调查

我刚刚自己搭了一个
https://www.yourworld.fun/Pixiv/
就是加载不出来....是香港机子啊

**Comment by mokeyjay** [comment]
你在你的机器上执行一下
`wget https://www.pixiv.net/ranking.php?mode=daily&p=1&format=json`
看能否拿到一个 json 数据。有很多 IDC 的 ip 端都被 pixiv 封掉了的

**Comment by xiaobailoves** [comment]
> 你在你的机器上执行一下
> `wget https://www.pixiv.net/ranking.php?mode=daily&p=1&format=json`
> 看能否拿到一个 json 数据。有很多 IDC 的 ip 端都被 pixiv 封掉了的

有json

**Comment by mokeyjay** [comment]
那检查一下目录权限吧，把日志打开，看看里面记录了什么

**Comment by xiaobailoves** [comment]
> 那检查一下目录权限吧，把日志打开，看看里面记录了什么

45.62.245.105 - - [21/May/2021:17:35:45 +0800] "GET https://www.yourworld.fun/Pixiv/ HTTP/1.1" 200 921 "https://www.yourworld.fun/Pixiv/" "Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/90.0.4430.212 Safari/537.36 Edg/90.0.818.62"[ZKLlT3]

**Comment by xiaobailoves** [comment]
> 那检查一下目录权限吧，把日志打开，看看里面记录了什么

刚刚我去吃了个饭抱歉哈

**Comment by xiaobailoves** [comment]
> 那检查一下目录权限吧，把日志打开，看看里面记录了什么

求解决啊！！！

**Comment by mokeyjay** [comment]
我的意思是开启我这个项目的日志功能，在 config.php 里，不是 http 的日志哈

**Comment by xiaobailoves** [comment]
我这里打开了
'log_level' => ['ERROR', 'DEBUG']
Log文件夹里没生成任何文件

**Comment by mokeyjay** [comment]
数组是需要用 [ ] 包裹的，你后面的做法是对的
如果连日志都没有，说明你本地目录权限有问题，文件无法写入

**Comment by xiaobailoves** [comment]
是不是虚拟机不能搭

**Comment by mokeyjay** [comment]
不会呀，vps 也是可以搭的，你正确设置一下目录权限应该就可以了
不过如果你说的是那种虚拟空间，那可能不行

**Comment by xiaobailoves** [comment]
> 不会呀，vps 也是可以搭的，你正确设置一下目录权限应该就可以了
> 不过如果你说的是那种虚拟空间，那可能不行

apache环境用不了,希望能兼容....
https://www.yourworld.fun/Pixiv/
我是虚拟空间所以源码里没有nginx环境所以导致无法加载
打扰咯!我希望你很快的进行兼容!
敬礼

**Comment by mokeyjay** [comment]
nginx 或 apache 并不影响本项目的使用
此外，https://cloud.mokeyjay.com/pixiv 已修复
