### ISSUE TITLE
可以安装,json可以获取,环境是apache调试模式下出现REQUEST_SCHEME

### ISSUE THREAD

**Issue by xiaobailoves** [mokeyjay/Pixiv-daily-ranking-widget#9]
![Snipaste_2021-05-21_22-40-12](https://user-images.githubusercontent.com/71917424/119209622-4a78ce00-bada-11eb-8b42-b346dcb5b51c.png)
既然支持那争取今天弄好吧

**Comment by mokeyjay** [comment]
更新一下 app/Libs/Tools.php 这个文件试试

**Comment by mokeyjay** [comment]
https://github.com/mokeyjay/Pixiv-daily-ranking-widget/commit/b835c742099b8cd80eff935678909c764bff7277

**Comment by xiaobailoves** [comment]
> 更新一下 app/Libs/Tools.php 这个文件试试

出现这个错误
Notice
: Undefined index: DOCUMENT_URI in
/home/ftp/s/serf1ld2lk3vxjx/wwwroot/Pixiv/app/Libs/Tools.php
on line
47

**Comment by mokeyjay** [comment]
> 更新一下 app/Libs/Tools.php 这个文件试试

再试试
